//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayAnhHN3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusAddDetail
    {
        public string CusFirstName { get; set; }
        public string CusLastName { get; set; }
        public string CusEmail { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Zip { get; set; }
        public string PhoneNum { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
